name: codspeed

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  codspeed-profiling:
    name: codspeed profiling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.12'
          cache: true

      - name: install deps
        run: |
          pdm venv create --with-pip --force $PYTHON
          pdm install -G testing -G testing-extra -G email

      # override pydantic-core from git - to report benchmarks
      # FIXME DO NOT MERGE THIS

      - uses: actions/checkout@v4
        with:
          repository: pydantic/pydantic-core
          ref: boxy/validator_serializer_reuse
          path: pydantic-core

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable

      - run: pdm run pip install ./pydantic-core

      # END

      - name: Run CodSpeed benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: pdm run pytest ./tests/benchmarks --codspeed
